# Generated by Django 4.1.1 on 2022-09-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MaisonEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('nom', models.CharField(max_length=50)),
                ('aliases', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeSquelette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couverture', models.ImageField(blank=True, upload_to='images/')),
                ('nom', models.CharField(max_length=50)),
                ('aliases', models.CharField(blank=True, max_length=50)),
                ('date_publication', models.DateTimeField()),
                ('description', models.TextField()),
                ('est_corrige', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteurs', models.ManyToManyField(to='recherches.auteur')),
                ('maison_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recherches.maisonedition')),
                ('matieres', models.ManyToManyField(to='recherches.matiere')),
                ('type_squelette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recherches.typesquelette')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
