# Generated by Django 4.1.1 on 2022-09-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['updated_at', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ('titre',),
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('aliases', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['updated_at', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MaisonEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['updated_at', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('nom', models.CharField(max_length=50)),
                ('aliases', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['updated_at', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SousQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(auto_created=True)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Sous Question',
                'verbose_name_plural': 'Sous Questions',
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='TypeSquelette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['updated_at', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(auto_created=True)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('sous_questions', models.ManyToManyField(blank=True, to='recherches.sousquestion')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couverture', models.ImageField(blank=True, upload_to='images/')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('aliases', models.CharField(blank=True, max_length=50)),
                ('date_publication', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('est_corrige', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('auteurs', models.ManyToManyField(blank=True, to='recherches.auteur')),
                ('chapitres', models.ManyToManyField(blank=True, to='recherches.chapitre')),
                ('classes', models.ManyToManyField(blank=True, to='recherches.classe')),
                ('maison_edition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recherches.maisonedition')),
                ('matieres', models.ManyToManyField(blank=True, to='recherches.matiere')),
                ('type_squelette', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recherches.typesquelette')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
        ),
        migrations.CreateModel(
            name='Exo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(auto_created=True)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('questions', models.ManyToManyField(blank=True, to='recherches.question')),
            ],
            options={
                'verbose_name': 'Exo',
                'verbose_name_plural': 'Exos',
                'ordering': ('numero',),
            },
        ),
        migrations.AddField(
            model_name='chapitre',
            name='exos',
            field=models.ManyToManyField(blank=True, to='recherches.exo'),
        ),
    ]
