# Generated by Django 4.1.1 on 2022-09-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recherches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='slugChap',
            new_name='slug',
        ),
    ]
