# Generated by Django 4.1.1 on 2022-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherches', '0002_alter_livre_auteurs_alter_livre_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
