# Generated by Django 4.1.1 on 2022-09-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recherches', '0002_rename_slugchap_chapitre_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='slug',
            new_name='slugChap',
        ),
    ]
