# Generated by Django 4.1.1 on 2022-09-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherches', '0003_alter_livre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='auteurs',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='maison_edition',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='matieres',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='type_squelette',
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
