# Generated by Django 4.1.1 on 2022-09-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recherches', '0004_remove_livre_auteurs_remove_livre_classes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exo',
        ),
    ]
